### ISSUE TITLE
RPi2 + mupen64plus + Load state = "Unhanded fault: alignment exception"

### ISSUE THREAD

**Issue by rcork** [RetroPie/RetroPie-Setup#1124]
Running the latest Retropie 3.2.1 SD image and using mupen64plus+rice for Super Mario 64. When i try to load state, mupen64plus crashes with an alignment exception. I found that if i use Retropie_Setup script to manually compile mupen64plus, then load state works. However, the latest version of mupen compile from source suffers from audio lag when using OMX audio (which is the default). Any suggestions?

**Comment by joolswills** [comment]
This is something best reported upstream probably. We do not develop/maintain all the emulators we ship with. @gizmo98 knows more about this than me.

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by HerbFargus** [comment]
I can confirm the same issue but yes should be sorted upstream as it's unrelated to RetroPie (unless there is some audio setting that was missed with the merges)

**Comment by gizmo98** [comment]
@rcork please try another video plugin and report if audio lag persists.

**Comment by objectchris** [comment]
anecdotally, i get the same audio lag issues with mupen64plus latest builds. eg on mario 64 i get a slight audio lag with the rice plugin (but the textures and lighting are off and it performs worse), and a lot of audio lag with the gles plugin (yet it performs and looks perfect).

were older versions using some sort of alternative audio plugin?

**Comment by gizmo98** [comment]
Please post your ricevideolinux.ini if mario64 is corrupted.

**Comment by gizmo98** [comment]
RiceVideoLinux.ini has to Mario64 entries. If your rom has another hash settings will not be applied. Mario64 needs ScreenUpdateSetting=6. 
```
{ff2b5a632623028b-45}
Name=SUPER MARIO 64
FastTextureCRC=1
AlternativeTxtSizeMethod=1
ScreenUpdateSetting=6

{36f03ca0d2c5c1bc-50}
Name=SUPER MARIO 64
FastTextureCRC=1
AlternativeTxtSizeMethod=1
ScreenUpdateSetting=6
```

**Comment by rcork** [comment]
@gizmo98 i always wondered about those hashes. They don't appear to be md5 hashes. How do we compare our roms to what's in RiceVideoLinux.ini?

**Comment by gizmo98** [comment]
I don't know how rice calculates the hash code. If you start a game rice adds the hash code of your game at the end of the file. So if you post the hash code i can add it.

**Comment by ScOULaris** [comment]
I can concur with what objectchris posted.

When running Mario 64 on the latest Mupen64plus binary in the latest RetroPie image using the gles plugin I get about a full second of audio lag. There is less audio lag with the rice plugin, but as he said the game's textures and lighting are inaccurate when using rice. The gles plugin is the only one of the three that runs the game properly, and this audio delay is the only problem with it.

It wasn't a problem in previous builds of Mupen64plus on RetroPie, from what I gather from YouTube videos and forum posts. I do believe that the audio plugin was recently changed, as I spotted a different name for it in the mupen64plus.cfg file in a YouTube video from a few months ago.

**Comment by gizmo98** [comment]
What's the problem with GLideN64? If you use a low screen resolution this plugin should run fine.

**Comment by ScOULaris** [comment]
@gizmo98 Oh, really? When I first ran it through Glide64 it was running at like 5fps and stretched across my whole 1080p screen. I'll look in the config file when I get home later tonight and try changing the resolution. Thanks.

**Comment by gizmo98** [comment]
If you start mario64 press x or m and set output screen resolution there.

**Comment by gizmo98** [comment]
@rcork please update RetroPie-Setup and do a source based installation again.

**Comment by ScOULaris** [comment]
@gizmo98 Are you talking about launching into the Retroarch options menu when using the Libretro version of Mupen64plus? If I set the default emulator to the standalone Mupen64plus_GlideN64 there and then change the resolution from that same menu, Mupen64 standalone will honor the resolution that I set?

I noticed that while both rice and gles plugins launch into Mario 64 at a 4:3 aspect ratio (not sure which resolution), GlideN64 by default stretches to fill the screen.

**Comment by rcork** [comment]
@gizmo98 Do you want me to use the Retropie SD image and then launch RetroPie setup and choose source, or use Rasbian, download RetroPie-Setup and do a clean source install?

**Comment by gizmo98** [comment]
@rcork close emulationstation with F4 key press and type:
```
cd RetroPie-Setup
git pull
sudo ./retropie_setup.sh
```
select option 5 "Install individualemulators". select mupen64plus and a source based installation.

@ScOULaris yeah when you launch a game.

**Comment by ScOULaris** [comment]
@gizmo98 So basically this is from the same menu where I select the default emulator, right? I'm changing the video mode to 640x480?

**Comment by gizmo98** [comment]
Yes.

**Comment by objectchris** [comment]
FYI my RiceVideoLinux.ini has the same settings for mario 64 as posted above. there's no new hashes at the end so I assume it's the right hash.

I should say the visual corruption is quite subtle - the alpha around the clouds in the beginning is ugly, the game looks slightly washed-out (lighting issue?), the fonts have a weird filtering effect that makes them look a bit ugly, and the frame rate is worse than gles, but still perfectly playable. I probably wouldn't know it's bad if I didn't have the gles to compare with!

also this sound issue affects mario kart 64 also. i'll try glide but if the performance is worse then it's probably going to be bad news for mario kart 64 - that game only just hangs on in multiplayer as it is!

**Comment by joolswills** [comment]
I have built new binaries for mupen64plus now since @gizmo98 's changes.

**Comment by HerbFargus** [comment]
I'll test them later when I have time. Hopefully the new binary fixes the load state crash

**Comment by gizmo98** [comment]
@objectchris there are differences between all video plugins and there is a rice plugin with even more visual issues. Please update mupen64plus. Audio lag should be better now. At least i hear no big delay between mario punching sound and visual apperance.

**Comment by ScOULaris** [comment]
@gizmo98 Update the mupen64plus binary or from source? Was a change recently applied that would fix the audio lag issue with the gles plugin?

**Comment by gizmo98** [comment]
@ScOULaris 
I reverted some changes. I removed the buffer underrun message a month ago. This modification seems to cause increased audio lag. Jools has already updated binaries.

**Comment by objectchris** [comment]
@gizmo98 
Just installed the latest binaries, but now i notice an error when it loads and then it quits out - saying it can't find 'libEGL.so' ?

![fullsizerender](https://cloud.githubusercontent.com/assets/13054748/11731998/cecd61e8-9f97-11e5-96f1-ccca1935c2b7.jpg)

**Comment by joolswills** [comment]
I accidently must have had raspbian libEGL installed again on one of my development chroots. I'll sort it.

**Comment by joolswills** [comment]
I have uploaded a new binary.

**Comment by ScOULaris** [comment]
Hm. I just updated to the newest binary, and I'm getting the same audio lag as before. I only tried Glide64 so far, but I'll test the gles plugin for audio lag when I get a chance later tonight.

**Comment by rcork** [comment]
Ok i updated Retropie, then compiled mupen from source, and load problem is fixed and OMX audio lag is gone. Looks like the code changes @gizmo98 made resolved the issue. I tried both rice and gles.

**Comment by ScOULaris** [comment]
So I'll need to update from source to get those code changes? I was under the impression that the binaries had been updated with them, so I updated my binary. The audio lag still persists afterward. When I have time to spare tomorrow I'll try updating from source. Is it necessary to update Retropie Setup beforehand? I just set mine all up and I'm a bit reluctant to update Retropie before I get more comfortable with it.

**Comment by joolswills** [comment]
I will rebuild binaries again, I may not have pulled in script changes when I built it as I didn't realise @gizmo98 had committed directly to retropie-setup with different github address for the audio driver

**Comment by HerbFargus** [comment]
Perhaps you should stick with the pc for n64 emulation if you arent comfortable with updates as the pi will always be hit and miss. 

For updating retropie: https://github.com/RetroPie/RetroPie-Setup/wiki/Updating-RetroPie

I can also confirm that lowering the video resolution to 640x480 on gliden64 vastly improves performance but still is sporadic.

**Comment by joolswills** [comment]
they are updated again.

**Comment by gizmo98** [comment]
@joolswills sorry for the confussion.

**Comment by joolswills** [comment]
NP. I hadn't been following the thread completely. Thanks for the contributions :)

**Comment by ScOULaris** [comment]
Updated my Retropie Setup Script and to the latest mupen64plus binaries, and the audio lag is gone. Thanks to both of you for addressing this issue. :)

**Comment by rcork** [comment]
I just tested the binaries and while audio lag is gone, the load state still causes an unaligned exception on Raspberry Pi 2.  If i compile from source, then it works perfectly. For now i'll just stick with compiling mupen myself.

**Comment by objectchris** [comment]
Updated setup script and just tried it both from a source recompile and binaries, and issue still seems to be there with gles2n64. eg, in mario kart 64 in the menus (seems to be the same in any game but obvious there when you should get a sound as soon as you press a button). Perhaps I've done something wrong?

**Comment by gizmo98** [comment]
Do you use hdmi audio?

**Comment by objectchris** [comment]
@gizmo98 Yes

**Comment by gizmo98** [comment]
Then i have no clue at the moment.

**Comment by HerbFargus** [comment]
as of https://github.com/RetroPie/RetroPie-Setup/commit/5db5c02e11c257fd4014d40b2309f5ccd6090c9f load state no longer crashes
