### ISSUE TITLE
Xbox One support for Model 1697/Firmware 2015

### ISSUE THREAD

**Issue by zerojay** [RetroPie/RetroPie-Setup#1275]
We've had various complaints about the latest firmware for Xbox One controllers causing them to go unrecognized by xboxdrv as well as a new model of controller that goes unrecognized.

I've updated my branch of xboxdrv to include the new USB device ID numbers and it should be all that's required to get these controllers working with Retropie.

Jools, can pull from my repo (http://github.com/zerojay/xboxdrv), compile and submit the updated xboxdrv binary as I mentioned earlier today?

**Comment by joolswills** [comment]
Will do, thanks. also users can always rebuild from the latest source by doing `sudo ./retropie_packages.sh xboxdrv`

**Comment by joolswills** [comment]
Done. thanks

**Comment by trixster1979** [comment]
This fix does not seem to work for me. I've updated the setup script, built xboxdrv from source but no luck. I've also tried installing the binary but that still doesn't help.

Attaching thr controller brings up a load of dialogue in the console, and jstest seems to recognise it too, but pressing the buttons does not toggle a response from jstest.

Emulationstation will not recognise that the pad is connected either.
