### ISSUE TITLE
3.7 Samba Shares not working in OSX

### ISSUE THREAD

**Issue by craigerskine** [RetroPie/RetroPie-Setup#1454]
Did the Samba protocols get updated in 3.7? It looks like there is an incompatibility with OSX as my shares are not connecting anymore. Others are seeing this too: https://discussions.apple.com/thread/7534687

**Comment by joolswills** [comment]
It's possible there was a Raspbian security update that has affected it. Note that RetroPie sits on top of Raspbian, so it is not something that is directly linked to RetroPie development.

you should `sudo apt-get update; sudo apt-get dist-upgrade` to see if any further updates help - but if it is a compatibility issue, there is nothing to do about it our end - perhaps there are some samba options that you could change though. I have no idea, and do not run OS X.

**Comment by JCrew7384** [comment]
I tried updating and unable to connect via shared drive in Mac or via smb. SSH through Mac works though.

**Comment by HerbFargus** [comment]
Tried updating what? Supposedly if you update samba to 4.4.3 it resolves it (https://discussions.apple.com/message/30176289#30176289) there are also workarounds referenced on the aforementioned thread. I don't have a Mac so I can't test it.

**Comment by JCrew7384** [comment]
Please ignore my noob status, how do I update Samba on the Raspberry Pi?

**Comment by joolswills** [comment]
you can't. you can work around the samba issue by adding a password for the pi user, and using that user for the shares. You might do best to ask on that apple forum if you need help to do this.

**Comment by JCrew7384** [comment]
I'll have to re read it. Maybe I mis understood. Isn't the password for the pi user just raspberry? I will check when back at my computer. Thanks for the comments.

**Comment by fmsarubbi** [comment]
The fix mentioned in the forum fixed it for me. 
https://retropie.org.uk/forum/topic/569/samba-apt-get-upgrade-samba-is-not-working-anymore/4

**Comment by joolswills** [comment]
Is this still an issue with the latest samba on Raspbian ? This post suggests it has been sorted https://www.raspberrypi.org/forums/viewtopic.php?p=998743#p998743

**Comment by joolswills** [comment]
If it is, I will enable the "pi" account for samba in the next image with the default password (or you can do it manually yourself with `echo -ne "raspberry\nraspberry\n" | sudo smbpasswd -s -a pi`

**Comment by prosthetichead** [comment]
issue was in my install i did last night adding the defualt pi user as jollswills said fixed issue and i can connect using smb now using pi/raspberry

**Comment by joolswills** [comment]
@prosthetichead please can you give me more details - did you update all the raspbian packages also ?

**Comment by prosthetichead** [comment]
Sorry.

No I didn't update any of the raspbian packages. It was a fresh install of retroPie, I tried using SMB shares to access the Pi but it would not accept a guest or the default pi/raspberry login. Quick google and I found this issue and your suggestion of running  `echo -ne "raspberry\nraspberry\n" | sudo smbpasswd -s -a pi` which enabled the pi/raspberry login and SMB has worked without issue since then on my mac.

**Comment by joolswills** [comment]
It would be useful if someone can test this with the latest raspbian samba packages without the workaround to confirm if it is still an issue or not.

**Comment by dankcushions** [comment]
Can confirm it's working in OSX without the workaround (which I never did). I have:
samba Version: 2:4.2.10+dfsg-0+deb8u3
samba-common-bin Version: 2:4.2.10+dfsg-0+deb8u3

not sure when i last updated but apparently I have the latest versions of both of these

**Comment by joolswills** [comment]
Thanks.

**Comment by dustinbolton** [comment]
Still not working with the latest RetroPie image on the site for Raspberry Pi 3 ( https://github.com/RetroPie/RetroPie-Setup/releases/download/3.8.1/retropie-v3.8.1-rpi2_rpi3.img.gz ).

**Comment by dankcushions** [comment]
The fix isn't in that image, which was released before it.

**Comment by diamondsw** [comment]
Fix still isn't in a fresh download of v4.1. Fail.

**Comment by joolswills** [comment]
@diamondsw it has been confirmed fixed by other users. If you need help please use the RetroPie forum https://retropie.org.uk/forum/

**Comment by diamondsw** [comment]
Apologies; just set up a brand new system with the 4.1 image from the site, fully updated via apt-get update/upgrade - and it didn't work until I found my way here and added the password via smbpasswd. I'll refer to the forums in the future.

**Comment by olivierlefloch** [comment]
I believe this is still an issue (latest OS X, latest retropie with all packages up to date).
