### ISSUE TITLE
Problem Font.cpp 

### ISSUE THREAD

**Issue by lucasmarsola** [RetroPie/RetroPie-Setup#2095]
I think this is a bug. When I open emulationstation, press any button, this happens:
`emulationstation: /home/marsola/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:129: static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&): Assertion `(c & 0xC0) != 0x80' failed. `

**Comment by drwhoelse** [comment]
I have similar issue.  This happened right after updating Retropie-Setup 4.2.18 and then updating everything within Retropie on my Intel i7 PC with Xubuntu 17.04 64-bit.

I have different result and error message.  ES crashes right after selecting any one of consoles, and then the screen stays black for a while (not showing gamelist yet).  The "es_log.txt" file doesn't have the error message for this.  Error is visible when using in terminal with emulationstation command... It reads:

emulationstation: /home/ubu/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:129: static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&): Assertion `(c & 0xC0) != 0x80' failed.
Aborted (core dumped)

By the way, Xubuntu 16.04.3 LTS 32-bit on my PC's second partition does not produce this error.

**Comment by EricFelbs** [comment]
I'm getting the same error it crashes every time I try to select an emulator

**Comment by falmear** [comment]
Starting program: /opt/retropie/supplementary/emulationstation/emulationstation 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe5a2f700 (LWP 16968)]
emulationstation: /home/retropie/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:132: static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&): Assertion `false' failed.

Thread 1 "emulationstatio" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff55bf37a in __GI_abort () at abort.c:89
#2  0x00007ffff55b5b47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x555555a9c389 "false", file=file@entry=0x555555ab3e20 "/home/retropie/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp", line=line@entry=132, 
    function=function@entry=0x555555ab4580 <Font::readUnicodeChar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long&)::__PRETTY_FUNCTION__> "static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&)")
    at assert.c:92
#3  0x00007ffff55b5bf2 in __GI___assert_fail (assertion=0x555555a9c389 "false", file=0x555555ab3e20 "/home/retropie/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp", line=132, 
    function=0x555555ab4580 <Font::readUnicodeChar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long&)::__PRETTY_FUNCTION__> "static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&)") at assert.c:101
#4  0x00005555558fa641 in Font::readUnicodeChar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long&) ()
#5  0x00005555558fd7b5 in Font::sizeText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float) ()
#6  0x00005555558e54c2 in TextComponent::calculateExtent() ()
#7  0x00005555558e570c in TextComponent::onTextChanged() ()
#8  0x00005555558e6421 in TextComponent::TextComponent(Window*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Font> const&, unsigned int, Alignment, Eigen::Matrix<float, 3, 1, 0, 3, 1>, Eigen::Matrix<float, 2, 1, 0, 2, 1>, unsigned int) ()
#9  0x00005555558d8d7d in HelpComponent::updateGrid() ()
#10 0x00005555558c322d in Window::setHelpPrompts(std::vector<std::pair<char const*, char const*>, std::allocator<std::pair<char const*, char const*> > > const&, HelpStyle const&) ()
#11 0x000055555588d772 in GuiComponent::updateHelpPrompts() ()
#12 0x0000555555866310 in std::_Function_handler<void (), ViewController::playViewTransition()::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#13 0x00005555558c4a0c in AnimationController::~AnimationController() ()
#14 0x00005555558c4a49 in AnimationController::~AnimationController() ()
#15 0x000055555588d108 in GuiComponent::advanceAnimation(unsigned char, unsigned int) ()
#16 0x000055555588d15a in GuiComponent::updateSelf(int) ()
#17 0x00005555558c230b in Window::update(int) ()
#18 0x0000555555784f4d in main ()

**Comment by Gyges-of-lydia** [comment]
+1 
(ubuntu 17.04)
fresh install.

**Comment by joolswills** [comment]
this should be opened here - https://github.com/RetroPie/EmulationStation/ but see https://github.com/RetroPie/EmulationStation/pull/226

**Comment by pjft** [comment]
Sorry for that.

If someone could test whether this PR effectively addresses it in Ubuntu, that would be extremely helpful as I have no access to an Ubuntu setup.

https://github.com/RetroPie/EmulationStation/pull/231

Thanks for flagging this, and apologies for the trouble.

**Comment by Gyges-of-lydia** [comment]
It Helped! i Updated from the setup script and it worked like charm! Many Many Thanks!

**Comment by drwhoelse** [comment]
I can confirm that ES V2.6.1RP is working properly on Xubuntu 17.04.
Doesn’t crash since then.  Happy camper here!

**Comment by joolswills** [comment]
This is resolved now.

**Comment by gaenserich** [comment]
I still get this error on ES 2.6.3rp on RetroPie 4.3 (RPi3). I've reinstalled and rebuilt from source several times to try to fix this, but still get this crash and error when browsing to the megadrive or pc pages:
```sh
emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:129: static UnicodeChar Font::readUnicodeChar(const string&, std::size_t&): Assertion `(c & 0xC0) != 0x80' failed.
Aborted
```
If I remove the megadrive or pc rom directories, the crash and error still come about when browsing to a different system page which previously hadn't caused the crash. Adding another system (ZX Spectrum) does not change this, either (that is, the crash and error still occur when attempting to open Megadrive or PC pages).

-I use the Selph Scraper with video thumbnail support, with the `images` directory and `gamelist.xml` file directly in the rom folders.

Other System Info:
`uname -a`: `Linux retropie 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`

`dpkg-query -W -f='${binary:Package} ${Version}\n'`:
```sh
acl 2.2.52-2
acpi-support-base 0.142-6
acpid 1:2.0.23-2
adduser 3.113+nmu3
advancecomp 1.19-1
alsa-utils 1.0.28-1
apt 1.0.9.8.4
apt-listchanges 2.85.13+nmu1
apt-transport-https 1.0.9.8.4
apt-utils 1.0.9.8.4
aptitude 0.6.11-1
aptitude-common 0.6.11-1
autoconf 2.69-8
automake 1:1.14.1-4+deb8u1
autopoint 0.19.3-2
autotools-dev 20140911.1
avahi-daemon 0.6.31-5
base-files 8+rpi1
base-passwd 3.5.37
bash 4.3-11+deb8u1
bash-completion 1:2.1-4
bind9-host 1:9.9.5.dfsg-9+deb8u13
binutils 2.25-5+deb8u1
bison 2:3.0.2.dfsg-2
bluetooth 5.23-2+rpi2
bluez 5.23-2+rpi2
bluez-firmware 1.2-3+rpi2
bsdmainutils 9.0.6
bsdutils 1:2.25.2-6
build-essential 11.7
bzip2 1.0.6-7
ca-certificates 20141019+deb8u3
cifs-utils 2:6.4-1
cmake 3.6.2-2~bpo8+1
cmake-data 3.6.2-2~bpo8+1
console-setup 1.123
console-setup-linux 1.123
coreutils 8.23-4
cpio 2.11+dfsg-4.1+deb8u1
cpp 4:4.9.2-2
cpp-4.9 4.9.2-10
cpufreqd 2.4.2-2
cpufrequtils 008-1
crda 3.13-1
cron 3.0pl1-127+deb8u1
curl 7.38.0-4+deb8u5
dash 0.5.7-4
dbus 1.8.22-0+deb8u1
dc 1.06.95-9
debconf 1.5.56+deb8u1
debconf-i18n 1.5.56+deb8u1
debconf-utils 1.5.56+deb8u1
debhelper 10.2.2~bpo8+1
debianutils 4.4
device-tree-compiler 1.4.1-1+rpi1
devscripts 2.15.3+deb8u1
dh-autoreconf 12~bpo8+1
dh-python 1.20141111-2
dh-strip-nondeterminism 0.003-1
dhcpcd5 6.7.1-1+rpi5
dialog 1.2-20140911-1
diffutils 1:3.3-1
dkms 2.2.0.3-2
dmidecode 2.12-3
dmsetup 2:1.02.90-2.2+deb8u1
dosfstools 3.0.27-1
dphys-swapfile 20100506-1
dpkg 1.17.27
dpkg-dev 1.17.27
e2fslibs:armhf 1.43.3-1~bpo8+1
e2fsprogs 1.43.3-1~bpo8+1
ed 1.10-2
evemu-tools 1.2.0-2
evtest 1:1.32-1
exfat-fuse 1.1.0-2+deb8u1
fake-hwclock 0.9
fakeroot 1.20.2-1
fbi 2.09-1
fbset 2.1-28
file 1:5.22+15-2+deb8u3
findutils 4.4.2-9
firmware-atheros 1:0.43+rpi6
firmware-brcm80211 1:0.43+rpi6
firmware-libertas 1:0.43+rpi6
firmware-ralink 1:0.43+rpi6
firmware-realtek 1:0.43+rpi6
flac 1.3.0-3
flex 2.5.39-8+deb8u2
fontconfig-config 2.11.0-6.3+deb8u1
fonts-dejavu-core 2.34-1
fonts-freefont-ttf 20120503-4
freepats 20060219-1
fuse 2.9.3-15+deb8u2
g++ 4:4.9.2-2
g++-4.9 4.9.2-10
gcc 4:4.9.2-2
gcc-4.6-base:armhf 4.6.4-5+rpi1
gcc-4.7-base:armhf 4.7.3-11+rpi1
gcc-4.8-base:armhf 4.8.4-1
gcc-4.9 4.9.2-10
gcc-4.9-base:armhf 4.9.2-10
gdb 7.7.1+dfsg-5+rpi1
gdbserver 7.7.1+dfsg-5+rpi1
geoip-database 20150317-1
gettext 0.19.3-2
gettext-base 0.19.3-2
ghostscript 9.06~dfsg-2+deb8u5
gifsicle 1.86-1
gir1.2-glib-2.0:armhf 1.42.0-2.2
git 1:2.1.4-2.1+deb8u4
git-man 1:2.1.4-2.1+deb8u4
gnupg 1.4.18-7+deb8u4
gpgv 1.4.18-7+deb8u4
grep 2.20-4.1
groff-base 1.22.2-8
gsfonts 1:8.11+urwcyr1.0.7~pre44-4.2
gzip 1.6-4
hardlink 0.3.0
hostname 3.15
htop 1.0.3-1
ifupdown 0.7.53.1
info 5.2.0.dfsg.1-6
init 1.22
init-system-helpers 1.22
initramfs-tools 0.120+deb8u3
initscripts 2.88dsf-59
inputattach 1:1.4.7-2
insserv 1.14.0-5
install-info 5.2.0.dfsg.1-6
intltool-debian 0.35.0+20060710.1
iproute2 3.16.0-2
iptables 1.4.21-2
iputils-ping 3:20121221-5
irqbalance 1.0.6-3+deb8u1
isc-dhcp-client 4.3.1-6+deb8u2
isc-dhcp-common 4.3.1-6+deb8u2
iso-codes 3.57-1
iw 3.17-1
joystick 1:1.4.7-2
jpegoptim 1.4.1-1
kbd 1.15.5-2
keyboard-configuration 1.123
klibc-utils 2.0.4-2+rpi1
kmod 18-3
less 458-3
lhasa 0.2.0+git3fe46-1+deb8u1
liba52-0.7.4 0.7.4-17
libacl1:armhf 2.2.52-2
libalgorithm-c3-perl 0.09-1
libalgorithm-diff-perl 1.19.02-3
libalgorithm-diff-xs-perl 0.04-3+b1
libalgorithm-merge-perl 0.08-2
libapr1:armhf 1.5.1-3
libaprutil1:armhf 1.5.4-1
libapt-inst1.5:armhf 1.0.9.8.4
libapt-pkg4.12:armhf 1.0.9.8.4
libarchive-extract-perl 0.72-1
libarchive-zip-perl 1.39-1
libarchive13:armhf 3.1.2-11+deb8u3
libasan1:armhf 4.9.2-10
libasound2:armhf 1.0.28-1+rpi3
libasound2-data 1.0.28-1+rpi3
libasound2-dev:armhf 1.0.28-1+rpi3
libasprintf0c2:armhf 0.19.3-2
libass5:armhf 0.10.2-3
libasyncns0:armhf 0.8-5
libatomic1:armhf 4.9.2-10
libattr1:armhf 1:2.4.47-2
libaudit-common 1:2.4-1
libaudit1:armhf 1:2.4-1
libavahi-client-dev 0.6.31-5
libavahi-client3:armhf 0.6.31-5
libavahi-common-data:armhf 0.6.31-5
libavahi-common-dev 0.6.31-5
libavahi-common3:armhf 0.6.31-5
libavahi-core7:armhf 0.6.31-5
libavc1394-0:armhf 0.5.4-2
libavcodec56:armhf 6:11.9-1~deb8u1+rpi1
libavformat56:armhf 6:11.9-1~deb8u1+rpi1
libavresample2:armhf 6:11.9-1~deb8u1+rpi1
libavutil54:armhf 6:11.9-1~deb8u1+rpi1
libbasicusageenvironment0 2014.01.13-1
libbind9-90 1:9.9.5.dfsg-9+deb8u13
libbison-dev:armhf 2:3.0.2.dfsg-2
libblkid1:armhf 2.25.2-6
libbluray1:armhf 1:0.9.3-3
libboost-atomic1.55.0:armhf 1.55.0+dfsg-3
libboost-chrono1.55.0:armhf 1.55.0+dfsg-3
libboost-date-time-dev:armhf 1.55.0.2
libboost-date-time1.55-dev:armhf 1.55.0+dfsg-3
libboost-date-time1.55.0:armhf 1.55.0+dfsg-3
libboost-filesystem-dev:armhf 1.55.0.2
libboost-filesystem1.55-dev:armhf 1.55.0+dfsg-3
libboost-filesystem1.55.0:armhf 1.55.0+dfsg-3
libboost-iostreams1.49.0 1.49.0-4+b2
libboost-iostreams1.50.0 1.50.0-1+b2
libboost-iostreams1.53.0 1.53.0-6+b2
libboost-iostreams1.54.0:armhf 1.54.0-5
libboost-iostreams1.55.0:armhf 1.55.0+dfsg-3
libboost-locale-dev:armhf 1.55.0.2
libboost-locale1.55-dev:armhf 1.55.0+dfsg-3
libboost-locale1.55.0:armhf 1.55.0+dfsg-3
libboost-serialization1.55-dev:armhf 1.55.0+dfsg-3
libboost-serialization1.55.0:armhf 1.55.0+dfsg-3
libboost-system-dev:armhf 1.55.0.2
libboost-system1.55-dev:armhf 1.55.0+dfsg-3
libboost-system1.55.0:armhf 1.55.0+dfsg-3
libboost-thread1.55.0:armhf 1.55.0+dfsg-3
libboost1.55-dev:armhf 1.55.0+dfsg-3
libbsd0:armhf 0.7.0-2
libbz2-1.0:armhf 1.0.6-7
libc-bin 2.19-18+deb8u10
libc-dev-bin 2.19-18+deb8u10
libc6:armhf 2.19-18+deb8u10
libc6-dbg:armhf 2.19-18+deb8u10
libc6-dev:armhf 2.19-18+deb8u10
libcaca-dev 0.99.beta19-2
libcaca0:armhf 0.99.beta19-2
libcap-ng0:armhf 0.7.4-2
libcap2:armhf 1:2.24-8
libcap2-bin 1:2.24-8
libcddb2 1.3.2-5
libcdio13 0.83-4.2
libcgi-fast-perl 1:2.04-1
libcgi-pm-perl 4.09-1
libchromaprint0:armhf 1.2-1
libclass-c3-perl 0.26-1
libclass-c3-xs-perl 0.13-2+b1
libcloog-isl4:armhf 0.18.2-1
libcomerr2:armhf 1.43.3-1~bpo8+1
libcpan-meta-perl 2.142690-1
libcpufreq0 008-1
libcroco3:armhf 0.6.8-3
libcryptsetup4:armhf 2:1.6.6-5
libcups2:armhf 1.7.5-11+deb8u1
libcupsfilters1:armhf 1.0.61-5+deb8u3+rpi1
libcupsimage2:armhf 1.7.5-11+deb8u1
libcurl3:armhf 7.38.0-4+deb8u5
libcurl3-gnutls:armhf 7.38.0-4+deb8u5
libcurl4-openssl-dev:armhf 7.38.0-4+deb8u5
libcwidget3:armhf 0.5.17-2
libdaemon0:armhf 0.14-6
libdata-optlist-perl 0.109-1
libdata-section-perl 0.200006-1
libdb5.3:armhf 5.3.28-9
libdbus-1-3:armhf 1.8.22-0+deb8u1
libdbus-1-dev:armhf 1.8.22-0+deb8u1
libdbus-glib-1-2:armhf 0.102-1
libdc1394-22:armhf 2.2.3-1
libdca0:armhf 0.0.5-7
libdebconfclient0:armhf 0.192
libdevmapper1.02.1:armhf 2:1.02.90-2.2+deb8u1
libdirectfb-1.2-9:armhf 1.2.10.0-5.1
libdirectfb-dev 1.2.10.0-5.1
libdirectfb-extra:armhf 1.2.10.0-5.1
libdns-export100 1:9.9.5.dfsg-9+deb8u13
libdns100 1:9.9.5.dfsg-9+deb8u13
libdpkg-perl 1.17.27
libdrm-amdgpu1:armhf 2.4.71-1+rpi1
libdrm-dev:armhf 2.4.71-1+rpi1
libdrm-exynos1:armhf 2.4.71-1+rpi1
libdrm-freedreno1:armhf 2.4.71-1+rpi1
libdrm-nouveau2:armhf 2.4.71-1+rpi1
libdrm-omap1:armhf 2.4.71-1+rpi1
libdrm-radeon1:armhf 2.4.71-1+rpi1
libdrm-tegra0:armhf 2.4.71-1+rpi1
libdrm2:armhf 2.4.71-1+rpi1
libdvbpsi9:armhf 1.2.0-1
libdvdnav4:armhf 5.0.1-1+deb8u1
libdvdread4:armhf 5.0.0-1
libebml4:armhf 1.3.0-2+deb8u1
libedit2:armhf 3.1-20140620-2
libeigen3-dev 3.2.2-3
libelf1:armhf 0.159-4.2
libelfg0:armhf 0.8.13-5
libenca0:armhf 1.16-1
liberror-perl 0.17-1.1
libestr0 0.1.9-1.1
libevemu1:armhf 1.2.0-2
libevent-2.0-5:armhf 2.0.21-stable-2+deb8u1
libexif12:armhf 0.6.21-2
libexpat1:armhf 2.1.0-6+deb8u4
libfaad2:armhf 2.7-8
libfakeroot:armhf 1.20.2-1
libfcgi-perl 0.77-1+deb8u1
libffi6:armhf 3.1-2+deb8u1
libfile-fcntllock-perl 0.22-1+b1
libfile-stripnondeterminism-perl 0.003-1
libfl-dev:armhf 2.5.39-8+deb8u2
libflac-dev:armhf 1.3.0-3
libflac8:armhf 1.3.0-3
libfluidsynth1:armhf 1.1.6-2
libfontconfig1:armhf 2.11.0-6.3+deb8u1
libfreeimage-dev 3.15.4-4.2+deb8u1
libfreeimage3 3.15.4-4.2+deb8u1
libfreetype6:armhf 2.6-2rpi1rpi1g
libfreetype6-dev 2.6-2rpi1rpi1g
libfribidi0:armhf 0.19.6-3
libfuse2:armhf 2.9.3-15+deb8u2
libgcc-4.9-dev:armhf 4.9.2-10
libgcc1:armhf 1:4.9.2-10
libgcrypt20:armhf 1.6.3-2+deb8u4
libgdbm3:armhf 1.8.3-13.1
libgeoip1:armhf 1.6.2-4
libgif4:armhf 4.1.6-11+deb8u1
libgirepository-1.0-1:armhf 1.42.0-2.2
libgl1-mesa-dev:armhf 13.0.0-1+rpi1
libgl1-mesa-dri:armhf 13.0.0-1+rpi1
libgl1-mesa-glx:armhf 13.0.0-1+rpi1
libglapi-mesa:armhf 13.0.0-1+rpi1
libglib2.0-0:armhf 2.42.1-1
libglib2.0-bin 2.42.1-1
libglib2.0-data 2.42.1-1
libglib2.0-dev 2.42.1-1
libglu1-mesa:armhf 9.0.0-2
libglu1-mesa-dev 9.0.0-2
libgmp10:armhf 2:6.0.0+dfsg-6+rpi1
libgnutls-deb0-28:armhf 3.3.8-6+deb8u7
libgnutls-openssl27:armhf 3.3.8-6+deb8u7
libgomp1:armhf 4.9.2-10
libgpg-error0:armhf 1.17-3
libgpm2:armhf 1.20.4-6.1
libgraphite2-3:armhf 1.3.10-1~deb8u1
libgroupsock1 2014.01.13-1
libgs9 9.06~dfsg-2+deb8u5
libgs9-common 9.06~dfsg-2+deb8u5
libgsm1:armhf 1.0.13-4
libgssapi-krb5-2:armhf 1.12.1+dfsg-19+deb8u2
libharfbuzz0b:armhf 0.9.35-2
libhogweed2:armhf 2.7.1-5+deb8u2
libice-dev:armhf 2:1.0.9-1
libice6:armhf 2:1.0.9-1
libicu52:armhf 52.1-8+deb8u5
libident 0.22-3
libidn11:armhf 1.29-1+deb8u2
libijs-0.35:armhf 0.35-10
libilmbase6:armhf 1.0.1-6.1
libirs-export91 1:9.9.5.dfsg-9+deb8u13
libisc-export95 1:9.9.5.dfsg-9+deb8u13
libisc95 1:9.9.5.dfsg-9+deb8u13
libisccc90 1:9.9.5.dfsg-9+deb8u13
libisccfg-export90 1:9.9.5.dfsg-9+deb8u13
libisccfg90 1:9.9.5.dfsg-9+deb8u13
libisl10:armhf 0.12.2-2
libiso9660-8 0.83-4.2
libiw30:armhf 30~pre9-8
libjack-jackd2-0:armhf 1.9.10+20140719git3eb0ae6a~dfsg-2
libjasper1:armhf 1.900.1-debian1-2.4+deb8u3
libjbig0:armhf 2.1-3.1
libjbig2dec0 0.13-4~deb8u2
libjim0.75:armhf 0.75-1
libjpeg-dev 1:1.3.1-12
libjpeg62-turbo:armhf 1:1.3.1-12
libjpeg62-turbo-dev:armhf 1:1.3.1-12
libjpeg8:armhf 8d1-2
libjson-c2:armhf 0.11-4
libjsoncpp0 0.6.0~rc2-3.1
libk5crypto3:armhf 1.12.1+dfsg-19+deb8u2
libkate1 0.4.1-4
libkeyutils1:armhf 1.5.9-5
libklibc 2.0.4-2+rpi1
libkmod2:armhf 18-3
libkrb5-3:armhf 1.12.1+dfsg-19+deb8u2
libkrb5support0:armhf 1.12.1+dfsg-19+deb8u2
liblcms2-2:armhf 2.6-3+deb8u1
libldap-2.4-2:armhf 2.4.40+dfsg-1+deb8u2
libldb1:armhf 2:1.1.20-0+deb8u1
liblhasa0:armhf 0.2.0+git3fe46-1+deb8u1
liblircclient0 0.9.0~pre1-1.2
liblivemedia23 2014.01.13-1
libllvm3.9:armhf 1:3.9-4
liblocale-gettext-perl 1.05-8+b1
liblockfile-bin 1.09-6
liblockfile1:armhf 1.09-6
liblog-message-perl 0.8-1
liblog-message-simple-perl 0.10-2
liblogging-stdlog0:armhf 1.0.4-1
liblognorm1:armhf 1.0.1-3
liblua5.2-0:armhf 5.2.3-1.1
libluajit-5.1-common 2.0.3+dfsg-3
liblwres90 1:9.9.5.dfsg-9+deb8u13
liblzma5:armhf 5.1.1alpha+20120614-2
liblzo2-2:armhf 2.08-1.2
libmad0:armhf 0.15.1b-8
libmad0-dev 0.15.1b-8
libmagic1:armhf 1:5.22+15-2+deb8u3
libmatroska6:armhf 1.4.1-2+deb8u1
libmikmod-config 3.3.7-1
libmikmod-dev:armhf 3.3.7-1
libmikmod3:armhf 3.3.7-1
libmng1:armhf 1.0.10+dfsg-3.1
libmodplug1 1:0.8.8.4-4.1
libmodule-build-perl 0.421000-2+deb8u1
libmodule-pluggable-perl 5.1-1
libmodule-signature-perl 0.73-1+deb8u2
libmount1:armhf 2.25.2-6
libmp3lame0:armhf 3.99.5+repack1-7+deb8u1
libmpc3:armhf 1.0.2-1
libmpcdec6:armhf 2:0.1~r459-4.1
libmpdec2:armhf 2.4.1-1
libmpeg2-4:armhf 0.5.1-7
libmpfr4:armhf 3.1.2-2
libmro-compat-perl 0.12-1
libmtp-common 1.1.8-1
libmtp9:armhf 1.1.8-1+b1
libncurses5:armhf 5.9+20140913-1
libncursesw5:armhf 5.9+20140913-1
libnettle4:armhf 2.7.1-5+deb8u2
libnewt0.52:armhf 0.52.17-1
libnfnetlink0:armhf 1.0.1-3
libnfsidmap2:armhf 0.25-5
libnih-dbus1 1.0.3-4.3
libnih1 1.0.3-4.3
libnl-3-200:armhf 3.2.24-2
libnl-genl-3-200:armhf 3.2.24-2
libnss-mdns:armhf 0.10-6
libntdb1:armhf 1.0-5
libogg-dev:armhf 1.3.2-1
libogg0:armhf 1.3.2-1
libopenal-data 1:1.15.1-5
libopenal1:armhf 1:1.15.1-5
libopenexr6:armhf 1.6.1-8
libopenjpeg5:armhf 1:1.5.2-3
libopts25:armhf 1:5.18.4-3
libopus0:armhf 1.1-2
liborc-0.4-0:armhf 1:0.4.22-1rpi1rpi1g
libp11-kit0:armhf 0.20.7-1
libpackage-constants-perl 0.04-1
libpam-modules:armhf 1.1.8-3.1+deb8u2+rpi3
libpam-modules-bin 1.1.8-3.1+deb8u2+rpi3
libpam-runtime 1.1.8-3.1+deb8u2+rpi3
libpam0g:armhf 1.1.8-3.1+deb8u2+rpi3
libpaper1:armhf 1.1.24+nmu4
libparams-util-perl 1.07-2+b1
libparted2:armhf 3.2-7
libpcre3:armhf 2:8.35-3.3+deb8u4
libpcre3-dev:armhf 2:8.35-3.3+deb8u4
libpcrecpp0:armhf 2:8.35-3.3+deb8u4
libpcsclite1:armhf 1.8.13-1+deb8u1
libpipeline1:armhf 1.4.0-1
libplymouth4:armhf 0.9.2-3+rpi1
libpng12-0:armhf 1.2.50-2+deb8u3
libpng12-dev:armhf 1.2.50-2+deb8u3
libpod-latex-perl 0.61-1
libpod-readme-perl 0.11-1
libpopt0:armhf 1.16-10
libpostproc52 6:0.git20120821-4
libprocps3:armhf 2:3.3.9-9
libproxy-tools 0.4.11-4
libproxy1:armhf 0.4.11-4
libpsl0:armhf 0.5.1-1
libpthread-stubs0-dev:armhf 0.3-4
libpulse-dev:armhf 5.0-13
libpulse-mainloop-glib0:armhf 5.0-13
libpulse0:armhf 5.0-13
libpython-stdlib:armhf 2.7.9-1
libpython2.7:armhf 2.7.9-2+deb8u1
libpython2.7-minimal:armhf 2.7.9-2+deb8u1
libpython2.7-stdlib:armhf 2.7.9-2+deb8u1
libpython3-stdlib:armhf 3.4.2-2
libpython3.4-minimal:armhf 3.4.2-1
libpython3.4-stdlib:armhf 3.4.2-1
libraspberrypi-bin 1.20170703-1
libraspberrypi-dev 1.20170703-1
libraspberrypi-doc 1.20170703-1
libraspberrypi0 1.20170703-1
libraw10:armhf 0.16.0-9+deb8u3
libraw1394-11:armhf 2.1.0-3
libreadline6:armhf 6.3-8
libregexp-common-perl 2013031301-1
libresid-builder0c2a 2.1.1-14
librtmp1:armhf 2.4+20150115.gita107cef-1+deb8u1
libsamplerate0:armhf 0.1.8-8
libsamplerate0-dev:armhf 0.1.8-8
libsasl2-2:armhf 2.1.26.dfsg1-13+deb8u1
libsasl2-modules:armhf 2.1.26.dfsg1-13+deb8u1
libsasl2-modules-db:armhf 2.1.26.dfsg1-13+deb8u1
libschroedinger-1.0-0:armhf 1.0.11-2.1
libsdl-mixer1.2:armhf 1.2.12-11+b1
libsdl-mixer1.2-dev:armhf 1.2.12-11+b1
libsdl-net1.2:armhf 1.2.8-4
libsdl-net1.2-dev:armhf 1.2.8-4
libsdl-sound1.2:armhf 1.0.3-7+b1
libsdl-sound1.2-dev:armhf 1.0.3-7+b1
libsdl1.2-dev 1.2.15-12rpi
libsdl1.2debian:armhf 1.2.15-12rpi
libsdl2-2.0-0:armhf 2.0.5+5rpi
libsdl2-dev:armhf 2.0.5+5rpi
libsdl2-mixer-2.0-0:armhf 2.0.0+dfsg1-5
libsdl2-mixer-dev:armhf 2.0.0+dfsg1-5
libselinux1:armhf 2.3-2
libsemanage-common 2.3-1
libsemanage1:armhf 2.3-1
libsepol1:armhf 2.3-2
libserf-1-1:armhf 1.3.8-1
libshine3:armhf 3.1.0-2.1
libshout3:armhf 2.3.1-3
libsidplay2 2.1.1-14
libsigc++-1.2-5c2 1.2.7-2+b1
libsigc++-2.0-0c2a:armhf 2.4.0-1
libsigsegv2:armhf 2.10-4
libslang2:armhf 2.3.0-2
libslang2-dev:armhf 2.3.0-2
libsm-dev:armhf 2:1.2.2-1
libsm6:armhf 2:1.2.2-1
libsmartcols1:armhf 2.25.2-6
libsmbclient:armhf 2:4.2.14+dfsg-0+deb8u8
libsndfile1:armhf 1.0.25-9.1+deb8u1
libsoftware-license-perl 0.103010-3
libspeex-dev:armhf 1.2~rc1.2-1
libspeex1:armhf 1.2~rc1.2-1
libspeexdsp-dev:armhf 1.2~rc1.2-1
libspeexdsp1:armhf 1.2~rc1.2-1
libsqlite3-0:armhf 3.8.7.1-1+deb8u2
libss2:armhf 1.43.3-1~bpo8+1
libssh-4:armhf 0.6.3-4+deb8u2
libssh2-1:armhf 1.4.3-4.1+deb8u1
libssl1.0.0:armhf 1.0.1t-1+deb8u6
libstdc++-4.9-dev:armhf 4.9.2-10
libstdc++6:armhf 4.9.2-10
libsub-exporter-perl 0.986-1
libsub-install-perl 0.928-1
libsvn1:armhf 1.8.10-6+deb8u5
libswscale3:armhf 6:11.9-1~deb8u1+rpi1
libsysfs2:armhf 2.1.0+repack-4
libsystemd0:armhf 215-17+deb8u7
libtag1-vanilla:armhf 1.9.1-2.1
libtag1c2a:armhf 1.9.1-2.1
libtalloc2:armhf 2.1.2-0+deb8u1
libtasn1-6:armhf 4.2-3+deb8u3
libtdb1:armhf 1.3.6-0+deb8u1
libterm-ui-perl 0.42-1
libtevent0:armhf 0.9.28-0+deb8u1
libtext-charwidth-perl 0.04-7+b4
libtext-iconv-perl 1.7-5+b5
libtext-soundex-perl 3.4-1+b2
libtext-template-perl 1.46-1
libtext-wrapi18n-perl 0.06-7
libtheora0:armhf 1.1.1+dfsg.1-6
libtiff5:armhf 4.0.3-12.3+deb8u4
libtimedate-perl 2.3000-2
libtinfo5:armhf 5.9+20140913-1
libtirpc1:armhf 0.2.5-1+deb8u1
libtool 2.4.2-1.11
libtwolame0 0.3.13-1.1
libtxc-dxtn-s2tc0:armhf 0~git20131104-1.1
libubsan0:armhf 4.9.2-10
libudev-dev:armhf 215-17+deb8u7
libudev0:armhf 175-7.2
libudev1:armhf 215-17+deb8u7
libunistring0:armhf 0.9.3-5.2
libupnp6 1:1.6.19+git20141001-1+deb8u1
libusageenvironment1 2014.01.13-1
libusb-0.1-4:armhf 2:0.1.12-25
libusb-1.0-0:armhf 2:1.0.19-1
libusb-1.0-0-dev:armhf 2:1.0.19-1
libustr-1.0-1:armhf 1.0.4-3
libuuid1:armhf 2.25.2-6
libv4l-0:armhf 1.6.0-2
libv4l2rds0:armhf 1.6.0-2
libv4lconvert0:armhf 1.6.0-2
libva1:armhf 1.7.3-2
libvcdinfo0 0.7.24+dfsg-0.2
libvlc-dev 2.2.6-1~deb8u1
libvlc5 2.2.6-1~deb8u1
libvlccore-dev 2.2.6-1~deb8u1
libvlccore8 2.2.6-1~deb8u1
libvorbis-dev:armhf 1.3.4-2
libvorbis0a:armhf 1.3.4-2
libvorbisenc2:armhf 1.3.4-2
libvorbisfile3:armhf 1.3.4-2
libvpx-dev:armhf 1.3.0-3+rvt
libvpx1:armhf 1.3.0-3+rvt
libwbclient0:armhf 2:4.2.14+dfsg-0+deb8u8
libwrap0:armhf 7.6.q-25
libx11-6:armhf 2:1.6.2-3
libx11-data 2:1.6.2-3
libx11-dev:armhf 2:1.6.2-3
libx11-doc 2:1.6.2-3
libx11-xcb-dev:armhf 2:1.6.2-3
libx11-xcb1:armhf 2:1.6.2-3
libx264-142:armhf 2:0.142.2431+gita5831aa-1+rpi2
libxapian22 1.2.19-1+deb8u1
libxau-dev:armhf 1:1.0.8-1
libxau6:armhf 1:1.0.8-1
libxcb-dri2-0:armhf 1.10-3
libxcb-dri2-0-dev:armhf 1.10-3
libxcb-dri3-0:armhf 1.10-3
libxcb-dri3-dev:armhf 1.10-3
libxcb-glx0:armhf 1.10-3
libxcb-glx0-dev:armhf 1.10-3
libxcb-present-dev:armhf 1.10-3
libxcb-present0:armhf 1.10-3
libxcb-randr0:armhf 1.10-3
libxcb-randr0-dev:armhf 1.10-3
libxcb-render0:armhf 1.10-3
libxcb-render0-dev:armhf 1.10-3
libxcb-shape0:armhf 1.10-3
libxcb-shape0-dev:armhf 1.10-3
libxcb-sync-dev:armhf 1.10-3
libxcb-sync1:armhf 1.10-3
libxcb-xfixes0:armhf 1.10-3
libxcb-xfixes0-dev:armhf 1.10-3
libxcb1:armhf 1.10-3
libxcb1-dev:armhf 1.10-3
libxcursor1:armhf 1:1.1.14-1
libxdamage-dev:armhf 1:1.1.4-2
libxdamage1:armhf 1:1.1.4-2
libxdmcp-dev:armhf 1:1.1.1-1
libxdmcp6:armhf 1:1.1.1-1
libxext-dev:armhf 2:1.3.3-1
libxext6:armhf 2:1.3.3-1
libxfixes-dev:armhf 1:5.0.1-2
libxfixes3:armhf 1:5.0.1-2
libxi6:armhf 2:1.7.4-1
libxinerama1:armhf 2:1.1.3-1
libxkbcommon-dev 0.4.3-2
libxkbcommon0:armhf 0.4.3-2
libxml2:armhf 2.9.1+dfsg1-5+deb8u5
libxmuu1:armhf 2:1.1.2-1
libxrandr2:armhf 2:1.4.2-1
libxrender1:armhf 1:0.9.8-1
libxshmfence-dev:armhf 1.1-4+rpi1
libxshmfence1:armhf 1.1-4+rpi1
libxslt1.1:armhf 1.1.28-2+deb8u3
libxss1:armhf 1:1.2.2-1
libxtables10 1.4.21-2
libxtst6:armhf 2:1.2.2-1
libxvidcore4:armhf 2:1.3.3-1
libxxf86vm-dev:armhf 1:1.1.3-1
libxxf86vm1:armhf 1:1.1.3-1
libzvbi-common 0.2.35-3
libzvbi0:armhf 0.2.35-3
linux-libc-dev:armhf 3.16.7-ckt11-1+deb8u4+rpi1
locales 2.19-18+deb8u10
lockfile-progs 0.1.17
login 1:4.2-3+deb8u4
logrotate 3.8.7-1
lsb-base 4.1+Debian13+rpi1+nmu1
lsb-release 4.1+Debian13+rpi1+nmu1
lua5.1 5.1.5-7.1
luajit 2.0.3+dfsg-3
m4 1.4.17-4
make 4.0-8.1
makedev 2.3.1-93
man-db 2.7.5-1~bpo8+1
manpages 3.74-1
manpages-dev 3.74-1
mawk 1.3.3-17
mc 3:4.8.13-3
mc-data 3:4.8.13-3
mesa-common-dev:armhf 13.0.0-1+rpi1
mime-support 3.58
module-init-tools 18-3
mount 2.25.2-6
mountall 2.54
multiarch-support 2.19-18+deb8u10
nano 2.2.6-3
ncdu 1.10-1
ncurses-base 5.9+20140913-1
ncurses-bin 5.9+20140913-1
ncurses-term 5.9+20140913-1
net-tools 1.60-26
netbase 5.3
netcat-openbsd 1.105-7
netcat-traditional 1.10-41
nfs-common 1:1.2.8-9
ntfs-3g 1:2014.2.15AR.2-1+deb8u3
ntp 1:4.2.6.p5+dfsg-7+deb8u2
omxplayer 0.3.7~git20160923~dfea8c9
openresolv 3.5.2-1
openssh-client 1:6.7p1-5+deb8u3
openssh-server 1:6.7p1-5+deb8u3
openssh-sftp-server 1:6.7p1-5+deb8u3
openssl 1.0.1t-1+deb8u6
optipng 0.7.5-1+deb8u1
p7zip-full 9.20.1~dfsg.1-4.1+deb8u2
parallel 20130922-1
parted 3.2-7
passwd 1:4.2-3+deb8u4
patch 2.7.5-1
perl 5.20.2-3+deb8u9
perl-base 5.20.2-3+deb8u9
perl-modules 5.20.2-3+deb8u9
pi-bluetooth 0.1.3+1
pkg-config 0.28-1
plymouth 0.9.2-3+rpi1
pmount 0.9.23-3
po-debconf 1.0.16+nmu3
poppler-data 0.4.7-1
procps 2:3.3.9-9
psmisc 22.21-2
python 2.7.9-1
python-apt 0.9.3.12
python-apt-common 0.9.3.12
python-crypto 2.6.1-5+deb8u1
python-dbus 1.2.0-2+b1
python-dbus-dev 1.2.0-2
python-gi 3.14.0-1
python-gobject 3.14.0-1
python-gobject-2 2.28.6-12
python-ldb 2:1.1.20-0+deb8u1
python-minimal 2.7.9-1
python-ntdb 1.0-5
python-pyudev 0.16.1-2
python-rpi.gpio 0.6.3~jessie-1
python-samba 2:4.2.14+dfsg-0+deb8u8
python-support 1.0.15
python-talloc 2.1.2-0+deb8u1
python-tdb 1.3.6-0+deb8u1
python2.7 2.7.9-2+deb8u1
python2.7-minimal 2.7.9-2+deb8u1
python3 3.4.2-2
python3-minimal 3.4.2-2
python3.4 3.4.2-1
python3.4-minimal 3.4.2-1
raspberrypi-bootloader 1.20170703-1
raspberrypi-kernel 1.20170703-1
raspberrypi-kernel-headers 1.20170703-1
raspberrypi-net-mods 1.2.5
raspberrypi-sys-mods 20170519
raspbian-archive-keyring 20120528.2
raspi-config 20170705
raspi-copies-and-fills 0.5-1
readline-common 6.3-8
rename 0.20-3
rng-tools 2-unofficial-mt.14-1
rpcbind 0.2.1-6+deb8u2
rsync 3.1.1-3
rsyslog 8.4.2-1+deb8u2
samba-common 2:4.2.14+dfsg-0+deb8u8
samba-common-bin 2:4.2.14+dfsg-0+deb8u8
samba-libs:armhf 2:4.2.14+dfsg-0+deb8u8
sed 4.2.2-4+deb8u1
sensible-utils 0.0.9
sgml-base 1.26+nmu4
shared-mime-info 1.3-1
ssh 1:6.7p1-5+deb8u3
startpar 0.59-3
strace 4.9-2
subversion 1.8.10-6+deb8u5
sudo 1.8.10p3-1+deb8u4
systemd 215-17+deb8u7
systemd-sysv 215-17+deb8u7
sysv-rc 2.88dsf-59
sysvinit-utils 2.88dsf-59
tar 1.27.1-2+deb8u1
tasksel 3.31+deb8u1
tasksel-data 3.31+deb8u1
tcpd 7.6.q-25
tmux 1.9-6
traceroute 1:2.0.20-2
triggerhappy 0.3.4-2
tzdata 2017b-0+deb8u1
ucf 3.0030
udev 215-17+deb8u7
unzip 6.0-16+deb8u3
usb-modeswitch 2.2.0+repack0-2
usb-modeswitch-data 20150115-1
usbmount 0.0.24
usbutils 1:007-2
util-linux 2.25.2-6
v4l-utils 1.6.0-2
vim-common 2:7.4.488-7+deb8u3
vim-tiny 2:7.4.488-7+deb8u3
vlc-data 2.2.6-1~deb8u1
vlc-nox 2.2.6-1~deb8u1
wget 1.16-1+deb8u2
whiptail 0.52.17-1
whois 5.2.7
wireless-regdb 2016.06.10-1~deb8u1
wireless-tools 30~pre9-8
wpasupplicant 2.3-1+deb8u4
x11-common 1:7.7+16
x11proto-core-dev 7.0.31-1
x11proto-damage-dev 1:1.2.1-2
x11proto-dri2-dev 2.8-2
x11proto-fixes-dev 1:5.0-2
x11proto-gl-dev 1.4.17-1
x11proto-input-dev 2.3.1-1
x11proto-kb-dev 1.0.6-2
x11proto-xext-dev 7.3.0-1
x11proto-xf86vidmode-dev 2.3.1-2
xauth 1:1.0.9-1
xdg-user-dirs 0.15-2
xkb-data 2.12-1
xml-core 0.13+nmu2
xmlstarlet 1.6.1-1
xorg-sgml-doctools 1:1.11-1
xtrans-dev 1.3.5-1
xz-utils 5.1.1alpha+20120614-2
zlib1g:armhf 1:1.2.8.dfsg-2
zlib1g-dev:armhf 1:1.2.8.dfsg-2
```

**Comment by pjft** [comment]
@gaenserich we might want to track this in a separate bug then.

Just to be clear, though, you're getting this error on a _Pi_? I haven't seen any such reports prior to this on a Pi, hence the question, as it might be slightly unrelated.

Does it happen when you install from the current binary? And what theme and system locale are you using, per chance?

If possible - I'm not sure what's the preference here - could you post this issue over at the actual EmulationStation tracker?

https://github.com/RetroPie/EmulationStation/issues

We'll follow up there as much as possible. It might be related to this prior problem, or it might be completely unrelated.

Thanks for raising this.

**Comment by gaenserich** [comment]
@pjft I respond here since with your edit you seem to think it may be relevant to this particular bug. Should I also post to the ES tracker, too (and thus duplicate the issue) or keep building this thread?

> Just to be clear, though, you're getting this error on a _Pi_?

Yes. A RPi 3.

> Does it happen when you install from the current binary?

Yes. I updated from binary yesterday, and its still throws this error.

> And what theme and system locale are you using, per chance?

Right now the Tronkyfran theme, but it shows the exact same error with default Carbon.

`locale`:
```sh
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
It occurs to me that not many English-speaking users would switch the locale from en_UK.UTF-8 (the default, correct?) Perhaps switching back to the default might shed some light on this situation.

**Comment by pjft** [comment]
The main reason I was suggesting to post in the ES tracker is because this bug has nothing to do with RetroPie-Setup, which is where this original bug had been mistakenly posted. As such, the wider RetroPie ES developer community won't be notified - or be made aware of it.

I don't think it is related to the original bug here. This was only happening on Linux, not on a Pi. And, as I said, the code that fixed the previous problem is still in place.

To expand on the issue, this usually happens because of some sort of mis-handling of a char* pointer. At the time, the instance that was causing this error on Linux was tackled, that's why I'm suggesting that while there may be the chance that it is related, it might be a completely new instance of it. 

The locale question was more to understand whether you'd be in a non-US/UK locale, which doesn't seem to be the case. Same goes for the them question.

Thanks.

I suppose I'll need to start asking more troubleshooting questions, then, as this doesn't seem to be extremely common, especially on a Pi.

Could you share the content of your es_settings.cfg file, and the last es_log.txt (or es_log.txt.bak) file that you'd have, from a session that crashed? Maybe those will share some insights into what the problem may be.

Also could you, if you have the chance, make a video of it happening, from the moment you start ES until it crashes, and not navigate especially quickly (so that in the video we can see what's happening on screen), and send it over? 

Sorry for the trouble, and thanks for attempting this. 

I don't personally mind continuing the conversation here, especially as I don't know what the best practice/recommended approach for this is. I still feel it would be useful to continue in the ES tracker, even if your first post just summarizes the issue and contains a link here, and then the follow up answer.

Your call, at least until we get more formal guidance from others.

Thanks.
